# -*- coding: utf-8 -*-
"""Los cuentos de Nordic Little Readers para 2.o de primaria (Starters).

G1 y G2 comparten nivel en el curso, pero no pueden compartir estanteria:
el nino de segundo ya leyo los seis de primero y necesita libro nuevo, no
el mismo otra vez.

Siguen la forma de los de G1 -frase corta, patron que se repite, algo que
se acumula- pero con una vuelta mas: la frase ya tiene dos partes y el
patron cambia al final del cuento, que es lo que hace que el nino note que
esta leyendo mejor que el ano pasado.

Se importan desde tools/build_readers.py, que es quien los dibuja.
"""

CUENTOS_STARTERS2 = [
{
 "id": "g2-u1", "grado": "G2", "tema": 1, "nivel": "Pre-A1",
 "titulo": "One, Two, Pip!",
 "objetivo": "Numbers 1 to 10",
 "paginas": [
  {"t": "One puffin. Where is he?", "clave": ["one"], "fondo": "garden",
   "piezas": [("char:starters:pip:1", .50, .68, .34)]},
  {"t": "Two balls. Red and blue.", "clave": ["two"], "fondo": "chess-plaza",
   "piezas": [("ball", .36, .74, .24), ("blue", .66, .74, .22)]},
  {"t": "Three cars. Go, go, go!", "clave": ["three"], "fondo": "chess-plaza",
   "piezas": [("car", .28, .76, .22), ("car", .50, .76, .22), ("car", .72, .76, .22)]},
  {"t": "Four friends. Hello, hello!", "clave": ["four"], "fondo": "entrance",
   "piezas": [("char:starters:freya:1", .20, .66, .48),
              ("char:starters:nico:1", .40, .66, .48),
              ("char:starters:astrid:1", .60, .66, .48),
              ("char:starters:tomas:1", .80, .66, .48)]},
  {"t": "Five kites. Up in the sky!", "clave": ["five"], "fondo": "picnic-garden",
   "piezas": [("kite", .18, .34, .20), ("kite", .38, .28, .20),
              ("kite", .58, .34, .20), ("kite", .78, .28, .20),
              ("kite", .92, .38, .18)]},
  {"t": "Six books. Big and small.", "clave": ["six"], "fondo": "library",
   "piezas": [("char:starters:astrid:6", .50, .66, .50)]},
  {"t": "Now count again. One, two, three...", "clave": ["count"], "fondo": "classroom",
   "piezas": [("char:starters:freya:5", .50, .64, .52)]},
  {"t": "But where is Pip? Pip is number seven!", "clave": ["seven"], "fondo": "classroom",
   "piezas": [("char:starters:pip:2", .50, .60, .32)]},
 ],
 "actividad": {"titulo": "Count with me",
  "instruccion": "Tap the picture you hear.",
  "items": [{"palabra": "ball", "img": "ball"},
            {"palabra": "car", "img": "car"},
            {"palabra": "kite", "img": "kite"},
            {"palabra": "bird", "img": "bird"}]},
},
{
 "id": "g2-u2", "grado": "G2", "tema": 2, "nivel": "Pre-A1",
 "titulo": "My Blue Bag",
 "objetivo": "Colours and my things",
 "paginas": [
  {"t": "This is my bag. My bag is blue.", "clave": ["bag", "blue"], "fondo": "classroom",
   "piezas": [("char:starters:nico:4", .34, .64, .52), ("suitcase", .72, .74, .24)]},
  {"t": "In my bag: one red ball.", "clave": ["red"], "fondo": "classroom",
   "piezas": [("red", .34, .72, .22), ("ball", .68, .74, .24)]},
  {"t": "In my bag: one yellow kite.", "clave": ["yellow"], "fondo": "classroom",
   "piezas": [("yellow", .34, .72, .22), ("kite", .68, .44, .26)]},
  {"t": "In my bag: two green socks.", "clave": ["green"], "fondo": "classroom",
   "piezas": [("green", .34, .72, .22), ("socks", .68, .74, .22)]},
  {"t": "In my bag: my teddy. He is brown.", "clave": ["teddy"], "fondo": "classroom",
   "piezas": [("teddy", .50, .70, .30)]},
  {"t": "My bag is full. It is very heavy!", "clave": ["full"], "fondo": "entrance",
   "piezas": [("char:starters:nico:8", .38, .66, .52), ("suitcase", .74, .74, .26)]},
  {"t": "Freya has a bag too. Her bag is small.", "clave": ["small"], "fondo": "entrance",
   "piezas": [("char:starters:freya:1", .38, .66, .52), ("pocket", .74, .74, .20)]},
  {"t": "In her bag: one pencil. That is all!", "clave": ["pencil"], "fondo": "entrance",
   "piezas": [("char:starters:freya:3", .50, .66, .52)]},
 ],
 "actividad": {"titulo": "What colour?",
  "instruccion": "Tap the colour you hear.",
  "items": [{"palabra": "red", "img": "red"},
            {"palabra": "blue", "img": "blue"},
            {"palabra": "green", "img": "green"},
            {"palabra": "yellow", "img": "yellow"}]},
},
{
 "id": "g2-u3", "grado": "G2", "tema": 3, "nivel": "Pre-A1",
 "titulo": "Astrid's Garden",
 "objetivo": "Plants and looking after them",
 "paginas": [
  {"t": "Astrid has a garden. It is very small.", "clave": ["garden"], "fondo": "garden",
   "piezas": [("char:starters:astrid:1", .50, .66, .54)]},
  {"t": "On Monday: one green plant.", "clave": ["monday", "green"], "fondo": "garden",
   "piezas": [("green", .50, .70, .24)]},
  {"t": "On Tuesday: water, water, water.", "clave": ["water"], "fondo": "garden",
   "piezas": [("char:starters:astrid:5", .50, .66, .52)]},
  {"t": "On Wednesday: a snail! Hello, snail.", "clave": ["snail"], "fondo": "garden",
   "piezas": [("snail", .40, .76, .18), ("char:starters:astrid:3", .74, .66, .48)]},
  {"t": "On Thursday: rain. Good for the plant.", "clave": ["rain"], "fondo": "garden",
   "piezas": [("rainy", .50, .40, .30)]},
  {"t": "On Friday: sun. Also good for the plant.", "clave": ["sun"], "fondo": "garden",
   "piezas": [("sunny", .50, .38, .30)]},
  {"t": "On Saturday: one little flower. Look!", "clave": ["flower"], "fondo": "garden",
   "piezas": [("char:starters:astrid:1", .38, .66, .50),
              ("char:starters:pip:1", .74, .72, .26)]},
  {"t": "On Sunday: Astrid does nothing. The garden is happy.",
   "clave": ["sunday"], "fondo": "picnic-garden",
   "piezas": [("char:starters:astrid:6", .50, .68, .50)]},
 ],
 "actividad": {"titulo": "In the garden",
  "instruccion": "Tap the picture you hear.",
  "items": [{"palabra": "snail", "img": "snail"},
            {"palabra": "bird", "img": "bird"},
            {"palabra": "rainy", "img": "rainy"},
            {"palabra": "sunny", "img": "sunny"}]},
},
{
 "id": "g2-u4", "grado": "G2", "tema": 4, "nivel": "Pre-A1",
 "titulo": "Tomas Can Jump",
 "objetivo": "What I can do",
 "paginas": [
  {"t": "I am Tomas. I can run. Look at me!", "clave": ["run"], "fondo": "track",
   "piezas": [("char:starters:tomas:7", .50, .66, .54)]},
  {"t": "I can jump. One, two, three - jump!", "clave": ["jump"], "fondo": "track",
   "piezas": [("char:starters:tomas:10", .50, .64, .54)]},
  {"t": "Can you climb? Yes, I can climb!", "clave": ["climb"], "fondo": "chess-plaza",
   "piezas": [("char:starters:tomas:7", .50, .66, .52)]},
  {"t": "Can you swim? Yes! I can swim.", "clave": ["swim"], "fondo": "mirador",
   "piezas": [("char:starters:tomas:2", .50, .66, .52)]},
  {"t": "Can you fly? No. I cannot fly.", "clave": ["fly"], "fondo": "garden",
   "piezas": [("char:starters:tomas:8", .50, .66, .52)]},
  {"t": "But Pip can fly! Look at Pip go!", "clave": ["fly"], "fondo": "garden",
   "piezas": [("char:starters:pip:4", .50, .40, .28)]},
  {"t": "Can Pip run? A little bit. Not fast.", "clave": ["run"], "fondo": "track",
   "piezas": [("char:starters:pip:1", .50, .72, .30)]},
  {"t": "We can all do one thing. That is enough!", "clave": ["all"], "fondo": "track",
   "piezas": [("char:starters:tomas:1", .28, .66, .48),
              ("char:starters:freya:1", .52, .66, .48),
              ("char:starters:pip:1", .78, .72, .26)]},
 ],
 "actividad": {"titulo": "Can you?",
  "instruccion": "Tap the picture you hear.",
  "items": [{"palabra": "bird", "img": "bird"},
            {"palabra": "fish", "img": "fish"},
            {"palabra": "monkey", "img": "monkey"},
            {"palabra": "rabbit", "img": "rabbit"}]},
},
{
 "id": "g2-u5", "grado": "G2", "tema": 5, "nivel": "Pre-A1",
 "titulo": "A Day at School",
 "objetivo": "My day",
 "paginas": [
  {"t": "In the morning: hello, school!", "clave": ["morning"], "fondo": "entrance",
   "piezas": [("char:starters:freya:1", .50, .66, .54)]},
  {"t": "At nine: we read a book.", "clave": ["read"], "fondo": "library",
   "piezas": [("char:starters:freya:6", .34, .66, .50),
              ("char:starters:nico:6", .68, .66, .50)]},
  {"t": "At ten: we sing a song.", "clave": ["sing"], "fondo": "amphitheater",
   "piezas": [("char:starters:astrid:5", .50, .66, .52)]},
  {"t": "At eleven: we run and jump.", "clave": ["run", "jump"], "fondo": "track",
   "piezas": [("char:starters:tomas:7", .38, .66, .50),
              ("char:starters:nico:7", .70, .66, .50)]},
  {"t": "At twelve: we eat. I am hungry!", "clave": ["eat"], "fondo": "picnic-garden",
   "piezas": [("char:starters:nico:6", .50, .68, .50)]},
  {"t": "At two: we paint. My hands are blue.", "clave": ["paint"], "fondo": "classroom",
   "piezas": [("char:starters:astrid:3", .38, .66, .50), ("blue", .74, .70, .22)]},
  {"t": "At three: goodbye, school! See you!", "clave": ["goodbye"], "fondo": "entrance",
   "piezas": [("char:starters:freya:10", .34, .66, .50),
              ("char:starters:tomas:10", .68, .66, .50)]},
  {"t": "At night: Pip is still at school. Good night, Pip.",
   "clave": ["night"], "fondo": "facade",
   "piezas": [("char:starters:pip:5", .50, .64, .30)]},
 ],
 "actividad": {"titulo": "My day",
  "instruccion": "Tap the picture you hear.",
  "items": [{"palabra": "book", "img": "museum"},
            {"palabra": "ball", "img": "ball"},
            {"palabra": "bird", "img": "bird"},
            {"palabra": "family", "img": "family"}]},
},
{
 "id": "g2-u6", "grado": "G2", "tema": 6, "nivel": "Pre-A1",
 "titulo": "Where Is Pip?",
 "objetivo": "In, on, under, behind",
 "paginas": [
  {"t": "It is a game. Find Pip! Ready?", "clave": ["find"], "fondo": "classroom",
   "piezas": [("char:starters:freya:5", .50, .64, .52)]},
  {"t": "Is Pip in the bag? No, he is not.", "clave": ["in"], "fondo": "classroom",
   "piezas": [("suitcase", .50, .74, .28)]},
  {"t": "Is Pip on the table? No, he is not.", "clave": ["on"], "fondo": "classroom",
   "piezas": [("char:starters:nico:4", .50, .64, .52)]},
  {"t": "Is Pip under the chair? No, he is not.", "clave": ["under"], "fondo": "library",
   "piezas": [("char:starters:astrid:6", .50, .66, .50)]},
  {"t": "Is Pip behind the door? No, he is not!", "clave": ["behind"], "fondo": "entrance",
   "piezas": [("char:starters:tomas:2", .50, .66, .52)]},
  {"t": "Is Pip in the garden? Look at the tree.", "clave": ["garden"], "fondo": "garden",
   "piezas": [("char:starters:freya:2", .34, .66, .50),
              ("char:starters:pip:1", .72, .48, .24)]},
  {"t": "There he is! Pip is IN the tree.", "clave": ["tree"], "fondo": "garden",
   "piezas": [("char:starters:pip:1", .50, .46, .30)]},
  {"t": "Good game, Pip. Now you find US!", "clave": ["game"], "fondo": "labyrinth",
   "piezas": [("char:starters:freya:10", .26, .66, .48),
              ("char:starters:nico:10", .50, .66, .48),
              ("char:starters:astrid:10", .74, .66, .48),
              ("char:starters:pip:3", .92, .72, .24)]},
 ],
 "actividad": {"titulo": "Where is it?",
  "instruccion": "Tap the picture you hear.",
  "items": [{"palabra": "bag", "img": "suitcase"},
            {"palabra": "bird", "img": "bird"},
            {"palabra": "ball", "img": "ball"},
            {"palabra": "teddy", "img": "teddy"}]},
},
]
